# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-30 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.CharField(default=0, max_length=500000),
            preserve_default=False,
        ),
    ]
